apiVersion: apps/v1
kind: Deployment
metadata:
  name: handlestring-deployment
  namespace: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: handlestring
  template:
    metadata:
      labels:
        app: handlestring
    spec:
      containers:
        - name: handlestring
          image: 192.168.0.47:80/wordpress/handlestring:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30    # 应用启动预热时间
            periodSeconds: 10          # 探测周期
            failureThreshold: 3        # 连续失败次数后重启容器
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: handlestring-service
  namespace: springboot
spec:
  type: ClusterIP  # 推荐：由 Ingress Controller 访问
  selector:
    app: handlestring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 30080  # 可选，但必须在 30000~32767 范围内 （type: NodePort，则需要配置这一行）
