apiVersion: apps/v1
kind: Deployment
metadata:
  name: handlestring-deployment
  namespace: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: handlestring
  template:
    metadata:
      labels:
        app: handlestring
    spec:
      containers:
        - name: handlestring
          image: 192.168.0.47:80/wordpress/handlestring:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120    # 应用启动预热时间
            periodSeconds: 10          # 探测周期
            failureThreshold: 5        # 连续失败次数后重启容器
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: handlestring-service
  namespace: springboot
spec:
  type: NodePort
  selector:
    app: handlestring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080