pipeline {
    agent any
    tools {
        maven 'Maven'  // 需要与Jenkins全局配置的中Maven的名称一致
        jdk 'JDK21'  // 需要与Jenkins全局配置的中JDK的名称一致
    }
    stages {
        // 检出代码
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Incool/coding-test.git',
                    branch: 'master'
            }
        }
        // 构建
        stage('Build') {
            steps {
                sh 'cd code-test/HandleString && mvn clean install'
            }
        }
        // 部署
        stage('Deploy') {
            steps {
                echo 'Starting Deploy...'
                // 1.使用scp
                sh '''
                    scp -o StrictHostKeyChecking=no code-test/HandleString/target/*.jar root@192.168.0.41:/root/app/
                    ssh -o StrictHostKeyChecking=no root@192.168.0.41 '
                                    cd /root/app &&
                                    chmod +x ExecScript.sh &&
                                    ./ExecScript.sh
                                '
                '''

//                 // 2.使用Publish Over SSH
//                 sshPublisher(
//                     publishers: [
//                         sshPublisherDesc(
//                             configName: '192.168.0.41-项目服务器',
//                             transfers: [
//                                 sshTransfer(
//                                     sourceFiles: '**/HandleString*.jar',
//                                     removePrefix: 'code-test/HandleString/target',
//                                     remoteDirectory: '',
//                                     execCommand: '''
//                                                     cd /root/app &&
//                                                     chmod +x ExecScript.sh &&
//                                                     ./ExecScript.sh
//                                                  '''
//                                 )
//                             ]
//                         )
//                     ]
//                 )
                echo 'Deploy Successful!!!'
            }
        }
    }
}